services:
  mariadb:
    image: mariadb:latest
    networks:
      - app-network
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: cats_shop
      MARIADB_PASSWORD: admin
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs-api
    env_file:
      - .env
    ports:
      - "8081:3000"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data:
